### ISSUE TITLE
Conflict with rails 2.3

### ISSUE THREAD

**Issue by jmvallet** [codyfauser/ebay#1]
It seems that there is a conflict between rails 2.3 and money 1.7.1.
Why ebay gem is only compatible with money 1.7.1 ?
Thanks.

**Comment by ouranos** [comment]
What is your problem ?
I've been using it with rails 2.3.4 without any issues. The only one I had was in cattr_accessor.rb but was patched in the version 0.12.

**Comment by dlindahl** [comment]
I, too, was using ebayapi 0.12 and money 1.7.1 without any problem until I tried to use Bundler. I'm not sure of the cattr_accessor error that you are referring to, but it appears to be back when using Bundler.

Anytime assert_select is used, I get this error:

```
NoMethodError: undefined method `id2name' for {:instance_writer=>false}:Hash
    money (1.7.1) lib/support/cattr_accessor.rb:7:in `cattr_reader'
    money (1.7.1) lib/support/cattr_accessor.rb:5:in `each'
    money (1.7.1) lib/support/cattr_accessor.rb:5:in `cattr_reader'
    money (1.7.1) lib/support/cattr_accessor.rb:54:in `cattr_accessor'
```

As well as:

```
NameError: uninitialized constant HTML::Document
```

Removing ebayapi and upgrading to the latest verison of money seems to fix both problems. But obviously I can't do that since I need ebayapi, and it needs money 1.7.1

I am by no means an expert, so if there is any other way around this apparent problem, please let me know! This is where I found out about what money was doing:

https://rails.lighthouseapp.com/projects/8994/tickets/1890
