### ISSUE TITLE
Problem With Ebay Client With Rails3 (unknown axis: ConvertedMaxBid)

### ISSUE THREAD

**Issue by HighOnRails** [codyfauser/ebay#10]
/var/lib/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/xxpath.rb:45:in `initialize': XPath (/ConvertedMaxBid/): unknown axis: ConvertedMaxBid (XML::XXPathError)
    from /var/lib/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/xxpath.rb:32:in`each'
    from /var/lib/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/xxpath.rb:32:in `initialize'
    from /ebay/lib/support/xml_mapping/money_node.rb:6:in`new'
    from /ebay/lib/support/xml_mapping/money_node.rb:6:in `initialize_impl'
    from /var/lib/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/mapping/base.rb:641:in`initialize'
    from (eval):2:in `new'
    from (eval):2:in`money_node'
    from /ebay/lib/ebay/types/bidding_details.rb:15
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /ebay/lib/ebay/types/item.rb:5
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /ebay/lib/ebay/requests/add_fixed_price_item.rb:1
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /ebay/lib/ebay/requests.rb:4
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /ebay/lib/ebay/ebay.rb:30
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /ebay/lib/ebay.rb:24
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /ebay/init.rb:1
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/plugin.rb:81
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/initializable.rb:25:in `instance_exec'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/initializable.rb:25:in`run'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/initializable.rb:50:in `run_initializers'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/initializable.rb:49:in`each'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/initializable.rb:49:in `run_initializers'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/application.rb:134:in`initialize!'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/application.rb:77:in `send'
    from /var/lib/gems/1.8/gems/railties-3.0.1/lib/rails/application.rb:77:in`method_missing'
    from /config/environment.rb:19
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /config.ru:3
    from /var/lib/gems/1.8/gems/rack-1.2.2/lib/rack/builder.rb:46:in `instance_eval'
    from /var/lib/gems/1.8/gems/rack-1.2.2/lib/rack/builder.rb:46:in`initialize'
    from /config.ru:1:in `new'
    from /config.ru:1

**Comment by dlindahl** [comment]
I am having the same problem. Any luck resolving the issue?

**Comment by neverender** [comment]
Me too.

**Comment by kewinwang** [comment]
Ah   me .toooo

**Comment by kewinwang** [comment]
this  is my solution :
kewin@office~/ebay_project/ebay-api/examples>sudo gem install xml-mapping -v=0.8.1
Successfully installed xml-mapping-0.8.1
1 gem installed
Installing ri documentation for xml-mapping-0.8.1...
Installing RDoc documentation for xml-mapping-0.8.1...
kewin@office~/ebay_project/ebay-api/examples>ls /usr/local/lib/ruby/gems/1.8/gems/xml-mapping-0.8.1/lib/xml/ -l
total 20
drwxr-xr-x 2 root root  4096 Aug 17 14:35 mapping
-rw------- 1 root root   511 Aug 17 14:35 mapping.rb
-rw------- 1 root root 11432 Aug 17 14:35 xxpath.rb
kewin@office~/ebay_project/ebay-api/examples>sudo chmod 755 /usr/local/lib/ruby/gems/1.8/gems/xml-mapping-0.8.1/lib/ -R
kewin@office~/ebay_project/ebay-api/examples>ruby get_my_messages.rb 
Sender: eBay Subject: eBay User ID Reminder
Sender: eBay Subject: Welcome to eBay.ca!

**Comment by kewinwang** [comment]
only xml-mapping-0.8.1    works  0.9.1 is not

**Comment by RevoHoffman** [comment]
I just created a fork that supports Rails 3 and Ruby 1.9.2. The problem I was encountering was that the RequesterCredentials were never being included in any of the requests. It worked fine in Ruby 1.8.7, but not in 1.9.2. The problem stemmed from this line /request/abstract.rb:

 object_node :requester_credentials, 'RequesterCredentials', :class => XMLRequesterCredentials, :optional => true

For reasons I don't fully understand, under Ruby 1.9.2, XML-Mapping isn't calling the requester_credentials method in Base.rb. So I moved it to Abstract.rb and it's working fine for me.

I'm guessing the issue is with the xml-mapping gem under 1.9.2, so my "fix" is just a hack. YMMV. My fork can be found at  https://github.com/Kynlyn/ebay
