### ISSUE TITLE
cannot load such file -- config (LoadError)

### ISSUE THREAD

**Issue by subhash-shah** [codyfauser/ebay#15]
Hi,

I am trying to run add_item.rb. I have already installed config 0.0.1. But when I execute the add_item.rb, I am getting following error:

/home/subhash/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- config (LoadError)
    from /home/subhash/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in`require'
    from add_item.rb:6:in `<main>'

I am new to ruby and may have missed something. Please help me resolve the issue.

Thanks

**Comment by bvogel** [comment]
Hi,
you don't run add_item directly, see the (no longer regularly available) documentation how to get started:
http://web.archive.org/web/20081120131712/http://www.codyfauser.com/articles/2006/11/22/ebay-api-client-for-ruby
basically you create a client instance and would run client.add_item on that.

HTH,
B.

**Comment by subhash-shah** [comment]
Thanks for the response. I have understood your point now. I have created the config file and a sample ruby file to get the time at eBay Server. Now, I am getting following message when I execute the sample ruby file to get eBay server time:

The API call "GeteBayTime" is invalid or not supported in this release.

The XML request is as below:
<?xml version='1.0' encoding='UTF-8'?><GeteBayTimeRequest xmlns='urn:ebay:apis:eBLBaseComponents'/>

I referred following link:
http://developer.ebay.com/DevZone/shopping/docs/CallRef/GeteBayTime.html

Can you please provide me your inputs on where I am doing anything wrong?

Thanks

**Comment by bvogel** [comment]
Hi,
this client only support the get_ebay_offical_time request, see https://github.com/codyfauser/ebay/tree/master/lib/ebay/requests

HTH,
B.

**Comment by subhash-shah** [comment]
Hi,

If I use the code with that request and response, I get following:
No XML <RequestPassword> or <RequestToken> was found in XML Request.

So, I thought I am not calling the API with correct request and response.

Thanks

**Comment by bvogel** [comment]
Two suggestions: either post some code or have a look at https://github.com/kayoom/ebay_client - the lib I ended up using/forking.

B.
