### ISSUE TITLE
error while loading lib

### ISSUE THREAD

**Issue by Olli** [codyfauser/ebay#5]
I use xml-mapping (0.9.1) and the gem ebayapi (0.12.0).
When i do require 'ebay' i got:

```
   XML::XXPathError: XPath (/ConvertedMaxBid/): unknown axis: ConvertedMaxBid
    from /usr/lib/ruby/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/xxpath.rb:45:in `initialize'
    from /usr/lib/ruby/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/xxpath.rb:32:in `each'
    from /usr/lib/ruby/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/xxpath.rb:32:in `initialize'
    from /usr/lib/ruby/gems/1.8/gems/ebayapi-0.12.0/lib/support/xml_mapping/money_node.rb:6:in `new'
    from /usr/lib/ruby/gems/1.8/gems/ebayapi-0.12.0/lib/support/xml_mapping/money_node.rb:6:in `initialize_impl'
    from /usr/lib/ruby/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/mapping/base.rb:641:in `initialize'
    from (eval):2:in `new'
    from (eval):2:in `money_node'
    from /usr/lib/ruby/gems/1.8/gems/ebayapi-0.12.0/lib/ebay/types/bidding_details.rb:15
```

....

**Comment by Olli** [comment]
This gives the solution i think
http://github.com/jkaneacumen/ebay/commit/59de245b2bd69ce9e4d644096983f2fccb2782dd

**Comment by tomash** [comment]
any change of getting this into upstream?

**Comment by jparbros** [comment]
I use xml-mapping 0.8.1 and it worked.

**Comment by michaelfranzl** [comment]
Confirmed, xml-mapping 0.8.1 works.

**Comment by marcojrfurtado** [comment]
This issue is similar to number 6.
