### ISSUE TITLE
Error in initialize.rb

### ISSUE THREAD

**Issue by Olli** [codyfauser/ebay#6]
For example i when i do:
    item = Ebay::Types::Item.new(
    :item_id => ARGV.first,
    :description => 'Revised Body' 
    )
i got:

  ArgumentError: wrong number of arguments (1 for 0)
        from /usr/lib/ruby/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/mapping/base.rb:170:in `initialize'
        from /usr/lib/ruby/gems/1.8/gems/xml-mapping-0.9.1/lib/xml/../xml/mapping/base.rb:170:in`initialize'
        from /usr/lib/ruby/gems/1.8/gems/ebayapi-0.12.0/lib/ebay/initializer.rb:4:in `initialize'
        from (irb):3:in`new'
        from (irb):3

**Comment by paulcookie** [comment]
i have the same problem

I really need a solution or hint with this problem

**Comment by rtomsmith** [comment]
I get this error running in the console with Rails 2.3.4 and attempting a simple get_ebay_official_time()

**Comment by clemcke** [comment]
Any solution to this yet?

**Comment by paulcookie** [comment]
use rebay by ccollins ))

**Comment by sweetnickyc** [comment]
(I'm a novice but) when I switched from xml-mapping 0.9.1 to xml-mapping 0.8.1 it began working. Looks like ebayapi is looking for anything >= 0.8.1, but there's some sort of breaking change that happened. Good luck.

**Comment by clemcke** [comment]
Fantastic, that fixed it for me.

**Comment by kenmickles** [comment]
Yeah, 0.8.1 works for me. Did run into this with it, though: http://www.lamnk.com/blog/computer/xml-mapping-gem-has-permission-problem/

**Comment by marcojrfurtado** [comment]
Thanks kenmickles. 

It still does not work with 0.9.1, but 0.8.1 is fine.
